name: Testes Web com WebdriverIO

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout do código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: 🧪 Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb || sudo apt-get -f install -y
          google-chrome --version

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🧹 Limpar diretório de relatórios (se aplicável)
        run: npm run pretest || echo "pretest não definido, ignorando..."

      - name: 🚀 Executar testes no modo headless
        env:
          HEADLESS: true
        run: npm run test

      - name: 📊 Gerar relatório Allure
        run: npm run allure:generate

      - name: 📁 Salvar relatório como artefato
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
